// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj7oDMUpy1FNkf-JL0rGJOWVqJtXA2dRY',
    appId: '1:352522623461:web:540f3d7e9d0ce898b1370c',
    messagingSenderId: '352522623461',
    projectId: 'todolist-16b25',
    authDomain: 'todolist-16b25.firebaseapp.com',
    storageBucket: 'todolist-16b25.appspot.com',
    measurementId: 'G-6Q1BXYZQ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lFyDKTvkbCAbe90K-D7Nfs9n9Te2dOI',
    appId: '1:352522623461:android:cc33705f8b9f640eb1370c',
    messagingSenderId: '352522623461',
    projectId: 'todolist-16b25',
    storageBucket: 'todolist-16b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgc0Z2AU1MyJmHYbQy7Jl19pZ5VH267Q',
    appId: '1:352522623461:ios:e0924488f0e61222b1370c',
    messagingSenderId: '352522623461',
    projectId: 'todolist-16b25',
    storageBucket: 'todolist-16b25.appspot.com',
    iosBundleId: 'com.sixamtech.stackFood',
  );
}
